17:39:48		Read 392 Global OptionSets
17:39:48		Read 1 SDK Messages
17:39:48		Completed Reading Metadata from Server - 00:00:06.7855169
17:39:48	Completed Reading Metadata from MetadataProviderService - 00:00:08.5226731
17:39:48	Begin Writing Code File
17:39:48	CrmSvcUtil Error: 2 : Exiting program with exit code 2 due to exception : System.Reflection.TargetParameterCountException: Parameter count mismatch.
17:39:48	   at System.Reflection.RuntimeMethodInfo.InvokeArgumentsCheck(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
17:39:48	   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
17:39:48	   at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters)
17:39:48	   at spkl.CrmSvcUtilExtensions.CodeGenerationService.Write(IOrganizationMetadata organizationMetadata, String language, String outputFile, String targetNamespace, IServiceProvider services)
17:39:48	   at Microsoft.Crm.Services.Utility.CrmSvcUtil.WriteCode(IOrganizationMetadata organizationMetadata)
17:39:48	   at Microsoft.Crm.Services.Utility.CrmSvcUtil.Run()
17:39:48	   at Microsoft.Crm.Services.Utility.CrmSvcUtil.Main(String[] args)
17:39:48	CrmSvcUtil Error: 2 : ===== DETAIL ======
17:39:48	CrmSvcUtil Error: 2 : Source	: mscorlib
17:39:48	Method	: InvokeArgumentsCheck
17:39:48	Date	: 17:39:48
17:39:48	Time	: 04/03/2025
17:39:48	Error	: Parameter count mismatch.
17:39:48	Stack Trace	: at System.Reflection.RuntimeMethodInfo.InvokeArgumentsCheck(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
17:39:48	   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
17:39:48	   at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters)
17:39:48	   at spkl.CrmSvcUtilExtensions.CodeGenerationService.Write(IOrganizationMetadata organizationMetadata, String language, String outputFile, String targetNamespace, IServiceProvider services)
17:39:48	   at Microsoft.Crm.Services.Utility.CrmSvcUtil.WriteCode(IOrganizationMetadata organizationMetadata)
17:39:48	   at Microsoft.Crm.Services.Utility.CrmSvcUtil.Run()
17:39:48	   at Microsoft.Crm.Services.Utility.CrmSvcUtil.Main(String[] args)
17:39:48	======================================================================================================================
17:39:48	
13:04:41	CrmSvcUtil : CRM Service Utility [Version 9.1.0.82]
13:04:41	c 2020 Microsoft Corporation. All rights reserved
13:04:41	
13:04:41	Loading config from 'C:\Vigence\Projects\Vig Internal\TextFormatter\packages\Microsoft.CrmSdk.CoreTools.9.1.0.79\content\bin\coretools\spkl.crmsvcutil.config'
13:04:48	Code written to C:\Vigence\Projects\Vig Internal\TextFormatter\TextFormatterPlugIns\EarlyBoundTypes.cs.
15:58:42	Microsoft.Xrm.Tooling.Connector.CrmServiceClient Error: 2 : Source	: mscorlib
15:58:42	Method	: ThrowIfExceptional
15:58:42	Date	: 04/09/2025
15:58:42	Time	: 15:58:42
15:58:42	Error	: One or more errors occurred.
15:58:42	Stack Trace	: at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
15:58:42	   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
15:58:42	   at System.Threading.Tasks.Task`1.get_Result()
15:58:42	   at Microsoft.Xrm.Tooling.Connector.CrmWebSvc.CreateFromResourceUrlAsync(Uri targetServiceUrl)
15:58:42	   at Microsoft.Xrm.Tooling.Connector.CrmWebSvc.GetAuthorityFromTargetService(Uri targetServiceUrl, CrmLogEntry logSink)
15:58:42	======================================================================================================================
15:58:42	Inner Exception Level 1	: 
15:58:42	Source	: mscorlib
15:58:42	Method	: ThrowForNonSuccess
15:58:42	Date	: 04/09/2025
15:58:42	Time	: 15:58:42
15:58:42	Error	: An error occurred while sending the request.
15:58:42	Stack Trace	: at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
15:58:42	   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
15:58:42	   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
15:58:42	   at Microsoft.IdentityModel.Clients.ActiveDirectory.Internal.Http.HttpClientWrapper.<GetResponseAsync>d__31.MoveNext()
15:58:42	--- End of stack trace from previous location where exception was thrown ---
15:58:42	   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
15:58:42	   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
15:58:42	   at Microsoft.IdentityModel.Clients.ActiveDirectory.AuthenticationParameters.<CreateFromResourceUrlCommonAsync>d__15.MoveNext()
15:58:42	--- End of stack trace from previous location where exception was thrown ---
15:58:42	   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
15:58:42	   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
15:58:42	   at Microsoft.IdentityModel.Clients.ActiveDirectory.AuthenticationParameters.<CreateFromResourceUrlAsync>d__12.MoveNext()
15:58:42	======================================================================================================================
15:58:42	Inner Exception Level 2	: 
15:58:42	Source	: System
15:58:42	Method	: EndGetResponse
15:58:42	Date	: 04/09/2025
15:58:42	Time	: 15:58:42
15:58:42	Error	: Unable to connect to the remote server
15:58:42	Stack Trace	: at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
15:58:42	   at System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)
15:58:42	======================================================================================================================
15:58:42	Inner Exception Level 3	: 
15:58:42	Source	: System
15:58:42	Method	: InternalEndConnect
15:58:42	Date	: 04/09/2025
15:58:42	Time	: 15:58:42
15:58:42	Error	: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond 51.137.137.159:443
15:58:42	Stack Trace	: at System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)
